
export const FETCH_AIRS = 'FETCH_AIRS'
export const FETCH_AIR = 'FETCH_AIR'
export const COUNT_CATE_AIRS = 'COUNT_CATE_AIRS'
export const MAKE_FOL_LIST = 'MAKE_FOL_LIST'
export const FETCH_CATE_AIRS = 'FETCH_CATE_AIRS'
export const SEND_REVIEW = 'SEND_REVIEW'

export const UPDATE_FOL = 'UPDATE_FOL'
export const DELETE_FOL = 'DELETE_FOL'
export const UPDATE_BLO  = 'UPDATE_BLO'
export const DELETE_BLO = 'DELETE_BLO'
export const GET_FOL = 'GET_FOL'
export const FETCH_FOL_AIRS = 'FETCH_FOL_AIRS'
export const FETCH_BLO_AIRS = 'FETCH_BLO_AIRS'

export const POST_PLACE = 'POST_PLACE'
export const POST_LIVE = 'POST_LIVE'
export const POST_DATA = 'POST_DATA'
export const SET_PLACE = 'SET_PLACE'

export const DRAWER_SET = 'DRAWER_SET'
export const DARKMODE_SET = 'DARKMODE_SET'
export const LIVEMODE_SET = 'LIVEMODE_SET'
export const FETCH_STREAMERS = 'FETCH_STREAMERS'
export const FETCH_STREAMER = 'FETCH_STREAMER'
export const DELETE_STREAMER = 'DELETE_STREAMER'
export const EDIT_STREAMER = 'EDIT_STREAMER'
export const CREATE_STREAMER = 'CREATE_STREAMER'
export const SEARCH_STREAMERS = 'SEARCH_STREAMERS'
export const CHECK_STREAMER = 'CHECK_STREAMER'

export const SIGN_UP = 'SIGN_UP'
export const ID_CHECK = 'ID_CHECK'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const RE_SIGN_IN = 'RE_SIGN_IN'
export const SIGN_IN_GOOGLE = 'SIGN_IN_GOOGLE'
export const SIGN_IN_NORMAL = 'SIGN_IN_NORMAL'

//to reduce typo

export const FETCH_SCHEDULELIST = 'FETCH_SCHEDULELIST'
export const FETCH_STREAMERLIST = 'FETCH_STREAMERLIST'
export const FETCH_STREAMER_PLATFORM = 'FETCH_STREAMER_PLATFORM'