
export const FETCH_AIRS = 'FETCH_AIRS'
export const FETCH_AIR = 'FETCH_AIR'

export const FETCH_STREAMERS = 'FETCH_STREAMERS'
export const FETCH_STREAMER = 'FETCH_STREAMER'
export const DELETE_STREAMER = 'DELETE_STREAMER'
export const EDIT_STREAMER = 'EDIT_STREAMER'
export const CREATE_STREAMER = 'CREATE_STREAMER'


//to reduce typo